"""Dummy offer letter generator (Phase 7 optional feature).

A company picks a **Selected** applicant and gets a templated, print-ready offer
letter populated with the student, drive and company details already on record.
Optional commercial terms (CTC, joining date, location) can be supplied per
letter; anything omitted renders as a clearly-marked placeholder so the document
never silently invents terms.

Output is HTML rather than PDF: PROJECT_CONTEXT allows either, and HTML avoids
adding a PDF dependency. The page carries print styling, so "Print → Save as
PDF" produces a clean A4 document.

The markup is assembled here rather than in a Jinja2 template because
PROJECT_CONTEXT limits Jinja2 to the single SPA entry point.
"""

from datetime import datetime
from html import escape

from backend.models import Application, ApplicationStatus, db
from backend.services.validators import ForbiddenError, NotFoundError

PLACEHOLDER = '<span style="color:#b02a37;">[to be confirmed]</span>'


def _value_or_placeholder(value: str | None) -> str:
    cleaned = (value or "").strip()
    return escape(cleaned) if cleaned else PLACEHOLDER


def get_selected_application(application_id: int) -> Application:
    """Fetch an application that is eligible for an offer letter."""
    application = db.session.get(Application, application_id)
    if application is None:
        raise NotFoundError(f"No application found with id {application_id}.")
    if application.status is not ApplicationStatus.SELECTED:
        raise ForbiddenError(
            "An offer letter can only be generated for a Selected candidate. "
            f"This application is currently {application.status.value}."
        )
    return application


def build_offer_letter(application: Application, details: dict | None = None) -> dict:
    """Return {'html': ..., 'filename': ...} for a selected candidate."""
    details = details or {}

    student = application.student
    user = student.user if student else None
    drive = application.drive
    company = drive.company if drive else None

    student_name = user.name if user else "The candidate"
    company_name = company.company_name if company else "The company"
    job_title = drive.job_title if drive else "the offered role"
    issued_on = datetime.now().strftime("%d %B %Y")

    ctc = _value_or_placeholder(details.get("ctc"))
    joining_date = _value_or_placeholder(details.get("joining_date"))
    location = _value_or_placeholder(details.get("location"))
    hr_contact = escape((company.hr_contact if company else None) or "the HR team")

    interview_line = ""
    if application.interview_datetime:
        interview_line = (
            f"<p>Following your interview on "
            f"{application.interview_datetime.strftime('%d %B %Y, %H:%M')}, we are "
            "pleased to confirm the outcome below.</p>"
        )

    html = f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8" />
<title>Offer letter — {escape(student_name)}</title>
<style>
  @page {{ size: A4; margin: 20mm; }}
  body {{ font-family: Georgia, 'Times New Roman', serif; color: #212529;
         line-height: 1.6; max-width: 780px; margin: 40px auto; padding: 0 24px; }}
  .banner {{ background: #fff3cd; border: 1px solid #ffe69c; color: #664d03;
             padding: 10px 14px; border-radius: 6px; font-family: Arial, sans-serif;
             font-size: 13px; margin-bottom: 28px; }}
  .letterhead {{ border-bottom: 3px solid #212529; padding-bottom: 12px; margin-bottom: 28px; }}
  .letterhead h1 {{ margin: 0; font-size: 26px; }}
  .meta {{ color: #6c757d; font-size: 14px; }}
  table.terms {{ border-collapse: collapse; margin: 20px 0; width: 100%; }}
  table.terms td {{ border: 1px solid #dee2e6; padding: 10px 12px; }}
  table.terms td:first-child {{ background: #f8f9fa; width: 38%; font-weight: bold; }}
  .signature {{ margin-top: 48px; }}
  @media print {{ .banner {{ background: #fff; border: 1px solid #999; }} }}
</style>
</head>
<body>
  <div class="banner">
    <strong>Specimen document.</strong> This offer letter is generated by the Placement
    Portal Application for demonstration purposes and is not a legally binding offer.
  </div>

  <div class="letterhead">
    <h1>{escape(company_name)}</h1>
    <div class="meta">Offer of Employment &middot; Issued {issued_on}</div>
  </div>

  <p><strong>To:</strong> {escape(student_name)}<br />
     <strong>Email:</strong> {escape(user.email if user else '—')}</p>

  <p>Dear {escape(student_name)},</p>

  {interview_line}

  <p>We are delighted to offer you the position of <strong>{escape(job_title)}</strong>
     at {escape(company_name)}, further to your application through the campus
     placement process.</p>

  <table class="terms">
    <tr><td>Position</td><td>{escape(job_title)}</td></tr>
    <tr><td>Company</td><td>{escape(company_name)}</td></tr>
    <tr><td>Annual CTC</td><td>{ctc}</td></tr>
    <tr><td>Date of joining</td><td>{joining_date}</td></tr>
    <tr><td>Work location</td><td>{location}</td></tr>
    <tr><td>Branch / CGPA</td>
        <td>{escape(student.branch or '—') if student else '—'} &middot;
            CGPA {escape(str(student.cgpa)) if student and student.cgpa is not None else '—'}</td></tr>
    <tr><td>Application reference</td><td>PPA-APP-{application.id}</td></tr>
  </table>

  <p>Please confirm your acceptance by replying to {hr_contact}. We look forward to
     welcoming you to the team.</p>

  <div class="signature">
    <p>Warm regards,<br />
       <strong>{escape(company_name)}</strong><br />
       {hr_contact}</p>
  </div>
</body>
</html>"""

    safe_name = "".join(
        char for char in student_name if char.isalnum() or char in (" ", "-", "_")
    ).strip().replace(" ", "_") or "candidate"

    return {"html": html, "filename": f"offer_letter_{safe_name}_{application.id}.html"}
